---
name: spod5
version: 0.02
author: ~
abstract: Turn pod into S5
license: perl
requires:
  Pod::POM: 0.17
  Pod::POM::View::HTML::Filter: 0.05
  Template: 2.08
  Test::More: 0
provides: {}
generated_by: Module::Build version 0.26
